language: generic
sudo: required
services:
    - docker

before_install:
    - docker  build -t ekowajar/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ekowajar/react-test npm test

after_success:
    - docker build -t ekowajar/multi-client ./client
    - docker build -t ekowajar/multi-nginx ./nginx
    - docker build -t ekowajar/multi-server ./server
    - docker build -t ekowajar/multi-worker ./worker
 
    # login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
    # take those images and push them up to docker hub
    - docker push ekowajar/multi-client
    - docker push ekowajar/multi-nginx
    - docker push ekowajar/multi-server
    - docker push ekowajar/multi-worker

